### ISSUE TITLE
Ability to use _commit=False broken

### ISSUE THREAD

**Issue by rsyring** [level12/keg-elements#60]
I believe #56 broke the ability to use `_commit` and `_flush` in `testing_create()`.

```
Traceback (most recent call last):
  File "/home/rsyring/projects/racebetter-src/racebetter/tests/test_toteupdates.py", line 60, in test_open_race
    race_ent = ents.Race.testing_create(race_status='Closed')
  File "/home/rsyring/projects/racebetter-src/racebetter/model/entities.py", line 93, in testing_create
    kwargs['event'] = Event.testing_create(_commit=False)
  File "/home/rsyring/.virtualenvs/racebetter/lib/python3.5/site-packages/keg_elements/db/mixins.py", line 217, in testing_create
    sorted(extra_kwargs))
AssertionError: Unknown column or relationship names in kwargs: ['_commit']
```

Reverting to KegElements 0.4.1 resolved my issue.

**Comment by nZac** [comment]
Two thoughts on this...

1. Anything starting with `_` shouldn't be included in the check for columns.
2. This functionality, checking that the kwargs passed are actually columns, should be it's own function and use the `keyword_optional` decorator so that we could reuse it somewhere else if we need to.
